<?php
require "back/init.php";
require "back/functions.php";
//var_dump($_SERVER);
if (!isset($_COOKIE["first"]))setcookie("first", "true");//nastavit cookie ktery oznamuje ze jsi prisel poprve. Uzitecne pro oznamovani o cookies a dalsi jine vecicky.
if (isset($_SESSION["user"])){//podiva se jestli je prihlaseny uzivatel
    var_dump($_SESSION["user"]);
}

echo "SUT";
if (isset($_POST["submitLog"])){
    login($db, $_POST["username"], $_POST["password"]);
}
if (isset($_POST["logout"])){
    unset($_SESSION["user"]);
    header("location: index.php");
}
if (isset($_FILES["userImage"])){
    
    changeImage($db, $_FILES["userImage"]);
    //change image function here
}

?>
<!DOCTYPE html>
<html lang="en">
    <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Projkov</title>
    <script src="jquery-4.0.0.js" ></script>
    <link rel="stylesheet" href="block/header.css">
</head>
<body>
    <br>
    <br>
    <br>
    <br>
    <nav>
        <div id="navLeft"><!--fill in hrefs when necessary, text is also changeable-->
            <a href="index.php">images</a><!--search and display images-->
            <a href="users.php">users</a><!--search for users-->
            <a href="tags.php">tags</a><!--edit tags individually-->
        </div>
        <div id="navRight">
            
            <?php
        if (!isset($_SESSION["user"])){//if not logged in, show register and login buttons
        ?>

            <form id="login"style="display:none"method="POST">
                <input class="logForm" name="username" id="nameLog" type="text" placeholder="username">
                <input class="logForm" name="password" id="passLog" type="text" placeholder="password"> 
                <input style="display:none"type="submit" name="submitLog"> 
            </form>
            <a id="log" href="#">login</a>

            <a id="reg" href="reg.php">register</a>
            <div id="settings"><!--settings here-->
                <div id="setButton"><div class="inset themeSelect"></div></div>
                <div id="themes">
                    <div id="whitemode" class="themeSelect"><div class="inset "></div></div>
                    <div id="darkmode" class="themeSelect"><div class="inset "></div></div>
                    <div id="bluemode" class="themeSelect"><div class="inset "></div></div>
                    <div id="darkblue" class="themeSelect"><div class="inset "></div></div>
                </div>
            </div>
            
            <?php
        }
        else{//if logged in, show profile PLS ADD CSS AND JS TO THIS AND MAKE IT LOOK GOOD
        ?>  
            <div id="nameplate">
                <div id="minimenu">
                    <div id="username"><?= $_SESSION["user"]["name"]?></div>
                    <div><img id="image" src=<?="'".$_SESSION["user"]["userImage"]."'"?> alt="user image"></div>
                </div>
                <div id="hidemenu">
                    <div id="userstuff">
                        <div id="usrinfo">
                            info here
                            <button id="logout">Log out</button>
                            <form method="post" style="display:none" name="lout" id="lout" > <input type="hidden" name="logout" value="OUT"> </form>
                        </div>

                        <div id="usrimg">
                            <form method="post" id="imageForm" name="imageForm" enctype="multipart/form-data">
                                <img id="usrimage" src=<?="'".$_SESSION["user"]["userImage"]."'"?> alt="user image">
                                <label for="userImage"></label>
                                <input accept="image/" type="file" name="userImage" id="userImage">
                            </form>
                        </div>
                    </div>
                    <div id="menuset">
                        <div id="thememenu">
                            <div id="whitemode" class="themeSelect"><div class="inset themeSelect"></div></div>
                            <div id="darkmode" class="themeSelect"><div class="inset themeSelect"></div></div>
                            <div id="bluemode" class="themeSelect"><div class="inset themeSelect"></div></div>
                            <div id="darkblue" class="themeSelect"><div class="inset themeSelect"></div></div>
                        </div>
                        </div>
                    </div>
                </div>
                <?php
            }
            ?>
        </div>
    </nav>
</body>
<script>
    $(document).ready(function(){
        //logic for login button stuff
        $("#log").click(()=>{
            console.log("GOO")
            if($("#regist").is(":visible")) $("#regist").toggle();
            if(!$("#nameLog").val()&&!$("#passLog").val()){
                $("#login").toggle();
            }
            else $("#login").submit();
        })
        /* rip 1 day of work
        //logic for register button stuff
        $("#reg").click(()=>{
            console.log("REE");
            if($("#login").is(":visible")) $("#login").toggle();
            if(!$("#nameReg").val()&&!$("#passReg").val()&&!$("#passReg2").val()){
                $("#regist").toggle();
            }
            else if ($("#passReg").val()===$("#passReg2").val()){
                    $("#regist").submit();
                }
                else{
                    $("#passReg").css("border", "red dashed 0.3rem");
                    $("#passReg2").css("border", "red dotted 0.3rem");
                }
        })*/
        //theme settings
        let theme;
        let name = 'theme=';
        let decodedCookie = decodeURIComponent(document.cookie);//decode from cookies
        let ca = decodedCookie.split(';');//break into arrays
        for(let i = 0; i <ca.length; i++) {//loop through arrays and search for
        let c = ca[i];

        while (c.charAt(0) === ' ') {
            c = c.substring(1);
        }
        if (c.indexOf(name) == 0) {
            console.log(c);
            theme =c.substring(name.length, c.length);
            }
        }
            
        console.log(theme);

        switch(theme){
            case "white":{
                    $(":root").animate("", "", ()=>{
                    $(":root").get(0).style.setProperty("--theme", "rgb(230, 88, 32)");
                    $(":root").get(0).style.setProperty("--primary", "rgb(250, 247, 240)");
                    $(":root").get(0).style.setProperty("--themeOrg", "rgb(209, 76, 23)");
                    $(":root").get(0).style.setProperty("--themePur", "rgb(142, 140, 216)");
                    document.cookie = "theme=white";
                });
                break;
            }
            case "dark":{
                $(":root").animate("", "", ()=>{
                    $(":root").get(0).style.setProperty("--theme", "rgb(230, 88, 32)");
                    $(":root").get(0).style.setProperty("--primary", "rgb(59, 59, 59)");
                    $(":root").get(0).style.setProperty("--themeOrg", "rgb(209, 76, 23)");
                    $(":root").get(0).style.setProperty("--themePur", "rgb(142, 140, 216)");
                    document.cookie = "theme=dark";
                });
                break;
            }
            case "blue":{
                    $(":root").animate("", "", ()=>{
                    $(":root").get(0).style.setProperty("--theme", "rgb(98, 117, 180)");
                    $(":root").get(0).style.setProperty("--primary", "rgb(250, 247, 240)");
                    $(":root").get(0).style.setProperty("--themeOrg", "rgb(89, 102, 145)");
                    $(":root").get(0).style.setProperty("--themePur", "rgb(230, 88, 32)");
                    document.cookie = "theme=blue";
                });
                break;
            }
            case "bluedark":{
                    $(":root").animate("", "", ()=>{
                    $(":root").get(0).style.setProperty("--theme", "rgb(98, 117, 180)");
                    $(":root").get(0).style.setProperty("--primary", "rgb(59, 59, 59)");
                    $(":root").get(0).style.setProperty("--themeOrg", "rgb(89, 102, 145)");
                    $(":root").get(0).style.setProperty("--themePur", "rgb(230, 88, 32)");
                    document.cookie = "theme=bluedark";
                });
                break;
            }

        }


        $("#setButton").click(()=>{
            console.log("SET");
            $("#themes").toggle();
            $("#themes").animate({
                height:'10rem'
            });

        })
        $("#whitemode").click(()=>{
            console.log("white");
                $(":root").animate("", "", ()=>{
                $(":root").get(0).style.setProperty("--theme", "rgb(230, 88, 32)");
                $(":root").get(0).style.setProperty("--primary", "rgb(250, 247, 240)");
                $(":root").get(0).style.setProperty("--themeOrg", "rgb(209, 76, 23)");
                $(":root").get(0).style.setProperty("--themePur", "rgb(142, 140, 216)");
                document.cookie = "theme=white";
            });
        })
        $("#darkmode").click(()=>{
            console.log("dark");
                $(":root").animate("", "", ()=>{
                $(":root").get(0).style.setProperty("--theme", "rgb(230, 88, 32)");
                $(":root").get(0).style.setProperty("--primary", "rgb(59, 59, 59)");
                $(":root").get(0).style.setProperty("--themeOrg", "rgb(209, 76, 23)");
                $(":root").get(0).style.setProperty("--themePur", "rgb(142, 140, 216)");
                document.cookie = "theme=dark";
            });
        })
        $("#bluemode").click(()=>{
            console.log("blue");
            $(":root").animate("", "", ()=>{
                $(":root").get(0).style.setProperty("--theme", "rgb(98, 117, 180)");
                $(":root").get(0).style.setProperty("--primary", "rgb(250, 247, 240)");
                $(":root").get(0).style.setProperty("--themeOrg", "rgb(89, 102, 145)");
                $(":root").get(0).style.setProperty("--themePur", "rgb(230, 88, 32)");
                document.cookie = "theme=blue";
            });
        })
        $("#darkblue").click(()=>{
            console.log("bluedark");
            $(":root").animate("", "", ()=>{
                $(":root").get(0).style.setProperty("--theme", "rgb(98, 117, 180)");
                $(":root").get(0).style.setProperty("--primary", "rgb(59, 59, 59)");
                $(":root").get(0).style.setProperty("--themeOrg", "rgb(89, 102, 145)");
                $(":root").get(0).style.setProperty("--themePur", "rgb(230, 88, 32)");
                document.cookie = "theme=bluedark";
            });
        })

        $("#minimenu").click(()=>{
            console.log("MIN")
            $("#username").toggle();
            $("#image").toggle();
            $("#hidemenu").animate({
                height:'toggle'
            });
        })
        $("#logout").click(()=>{//works
            $("#lout").submit();
            console.log("LOG");
        })

        //submit immediately after giving file... doesn't work for some reason ;-;
        //I hate css ;-; I want to cry ;-;
        $("#userImage").change(function(){
            $("#imageForm").submit();
        })
        
    });
    </script>
<?php
var_dump($_FILES); echo"<br><br>"?>